// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: remote.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Prometheus {

  /// <summary>Holder for reflection information generated from remote.proto</summary>
  public static partial class RemoteReflection {

    #region Descriptor
    /// <summary>File descriptor for remote.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RemoteReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxyZW1vdGUucHJvdG8SCnByb21ldGhldXMaC3R5cGVzLnByb3RvGhRnb2dv",
            "cHJvdG8vZ29nby5wcm90byJACgxXcml0ZVJlcXVlc3QSMAoKdGltZXNlcmll",
            "cxgBIAMoCzIWLnByb21ldGhldXMuVGltZVNlcmllc0IEyN4fACIxCgtSZWFk",
            "UmVxdWVzdBIiCgdxdWVyaWVzGAEgAygLMhEucHJvbWV0aGV1cy5RdWVyeSI4",
            "CgxSZWFkUmVzcG9uc2USKAoHcmVzdWx0cxgBIAMoCzIXLnByb21ldGhldXMu",
            "UXVlcnlSZXN1bHQijwEKBVF1ZXJ5EhoKEnN0YXJ0X3RpbWVzdGFtcF9tcxgB",
            "IAEoAxIYChBlbmRfdGltZXN0YW1wX21zGAIgASgDEioKCG1hdGNoZXJzGAMg",
            "AygLMhgucHJvbWV0aGV1cy5MYWJlbE1hdGNoZXISJAoFaGludHMYBCABKAsy",
            "FS5wcm9tZXRoZXVzLlJlYWRIaW50cyI5CgtRdWVyeVJlc3VsdBIqCgp0aW1l",
            "c2VyaWVzGAEgAygLMhYucHJvbWV0aGV1cy5UaW1lU2VyaWVzQghaBnByb21w",
            "YmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Prometheus.TypesReflection.Descriptor, global::Gogoproto.GogoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Prometheus.WriteRequest), global::Prometheus.WriteRequest.Parser, new[]{ "Timeseries" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Prometheus.ReadRequest), global::Prometheus.ReadRequest.Parser, new[]{ "Queries" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Prometheus.ReadResponse), global::Prometheus.ReadResponse.Parser, new[]{ "Results" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Prometheus.Query), global::Prometheus.Query.Parser, new[]{ "StartTimestampMs", "EndTimestampMs", "Matchers", "Hints" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Prometheus.QueryResult), global::Prometheus.QueryResult.Parser, new[]{ "Timeseries" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WriteRequest : pb::IMessage<WriteRequest> {
    private static readonly pb::MessageParser<WriteRequest> _parser = new pb::MessageParser<WriteRequest>(() => new WriteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WriteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Prometheus.RemoteReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WriteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WriteRequest(WriteRequest other) : this() {
      timeseries_ = other.timeseries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WriteRequest Clone() {
      return new WriteRequest(this);
    }

    /// <summary>Field number for the "timeseries" field.</summary>
    public const int TimeseriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Prometheus.TimeSeries> _repeated_timeseries_codec
        = pb::FieldCodec.ForMessage(10, global::Prometheus.TimeSeries.Parser);
    private readonly pbc::RepeatedField<global::Prometheus.TimeSeries> timeseries_ = new pbc::RepeatedField<global::Prometheus.TimeSeries>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Prometheus.TimeSeries> Timeseries {
      get { return timeseries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WriteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WriteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!timeseries_.Equals(other.timeseries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= timeseries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      timeseries_.WriteTo(output, _repeated_timeseries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += timeseries_.CalculateSize(_repeated_timeseries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WriteRequest other) {
      if (other == null) {
        return;
      }
      timeseries_.Add(other.timeseries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            timeseries_.AddEntriesFrom(input, _repeated_timeseries_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReadRequest : pb::IMessage<ReadRequest> {
    private static readonly pb::MessageParser<ReadRequest> _parser = new pb::MessageParser<ReadRequest>(() => new ReadRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReadRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Prometheus.RemoteReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadRequest(ReadRequest other) : this() {
      queries_ = other.queries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadRequest Clone() {
      return new ReadRequest(this);
    }

    /// <summary>Field number for the "queries" field.</summary>
    public const int QueriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Prometheus.Query> _repeated_queries_codec
        = pb::FieldCodec.ForMessage(10, global::Prometheus.Query.Parser);
    private readonly pbc::RepeatedField<global::Prometheus.Query> queries_ = new pbc::RepeatedField<global::Prometheus.Query>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Prometheus.Query> Queries {
      get { return queries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReadRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReadRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!queries_.Equals(other.queries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= queries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      queries_.WriteTo(output, _repeated_queries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += queries_.CalculateSize(_repeated_queries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReadRequest other) {
      if (other == null) {
        return;
      }
      queries_.Add(other.queries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            queries_.AddEntriesFrom(input, _repeated_queries_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReadResponse : pb::IMessage<ReadResponse> {
    private static readonly pb::MessageParser<ReadResponse> _parser = new pb::MessageParser<ReadResponse>(() => new ReadResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReadResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Prometheus.RemoteReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadResponse(ReadResponse other) : this() {
      results_ = other.results_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadResponse Clone() {
      return new ReadResponse(this);
    }

    /// <summary>Field number for the "results" field.</summary>
    public const int ResultsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Prometheus.QueryResult> _repeated_results_codec
        = pb::FieldCodec.ForMessage(10, global::Prometheus.QueryResult.Parser);
    private readonly pbc::RepeatedField<global::Prometheus.QueryResult> results_ = new pbc::RepeatedField<global::Prometheus.QueryResult>();
    /// <summary>
    /// In same order as the request's queries.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Prometheus.QueryResult> Results {
      get { return results_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReadResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReadResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!results_.Equals(other.results_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= results_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      results_.WriteTo(output, _repeated_results_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += results_.CalculateSize(_repeated_results_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReadResponse other) {
      if (other == null) {
        return;
      }
      results_.Add(other.results_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            results_.AddEntriesFrom(input, _repeated_results_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Query : pb::IMessage<Query> {
    private static readonly pb::MessageParser<Query> _parser = new pb::MessageParser<Query>(() => new Query());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Query> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Prometheus.RemoteReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Query() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Query(Query other) : this() {
      startTimestampMs_ = other.startTimestampMs_;
      endTimestampMs_ = other.endTimestampMs_;
      matchers_ = other.matchers_.Clone();
      hints_ = other.hints_ != null ? other.hints_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Query Clone() {
      return new Query(this);
    }

    /// <summary>Field number for the "start_timestamp_ms" field.</summary>
    public const int StartTimestampMsFieldNumber = 1;
    private long startTimestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long StartTimestampMs {
      get { return startTimestampMs_; }
      set {
        startTimestampMs_ = value;
      }
    }

    /// <summary>Field number for the "end_timestamp_ms" field.</summary>
    public const int EndTimestampMsFieldNumber = 2;
    private long endTimestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long EndTimestampMs {
      get { return endTimestampMs_; }
      set {
        endTimestampMs_ = value;
      }
    }

    /// <summary>Field number for the "matchers" field.</summary>
    public const int MatchersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Prometheus.LabelMatcher> _repeated_matchers_codec
        = pb::FieldCodec.ForMessage(26, global::Prometheus.LabelMatcher.Parser);
    private readonly pbc::RepeatedField<global::Prometheus.LabelMatcher> matchers_ = new pbc::RepeatedField<global::Prometheus.LabelMatcher>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Prometheus.LabelMatcher> Matchers {
      get { return matchers_; }
    }

    /// <summary>Field number for the "hints" field.</summary>
    public const int HintsFieldNumber = 4;
    private global::Prometheus.ReadHints hints_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Prometheus.ReadHints Hints {
      get { return hints_; }
      set {
        hints_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Query);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Query other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartTimestampMs != other.StartTimestampMs) return false;
      if (EndTimestampMs != other.EndTimestampMs) return false;
      if(!matchers_.Equals(other.matchers_)) return false;
      if (!object.Equals(Hints, other.Hints)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StartTimestampMs != 0L) hash ^= StartTimestampMs.GetHashCode();
      if (EndTimestampMs != 0L) hash ^= EndTimestampMs.GetHashCode();
      hash ^= matchers_.GetHashCode();
      if (hints_ != null) hash ^= Hints.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StartTimestampMs != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StartTimestampMs);
      }
      if (EndTimestampMs != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(EndTimestampMs);
      }
      matchers_.WriteTo(output, _repeated_matchers_codec);
      if (hints_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Hints);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StartTimestampMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartTimestampMs);
      }
      if (EndTimestampMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTimestampMs);
      }
      size += matchers_.CalculateSize(_repeated_matchers_codec);
      if (hints_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Hints);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Query other) {
      if (other == null) {
        return;
      }
      if (other.StartTimestampMs != 0L) {
        StartTimestampMs = other.StartTimestampMs;
      }
      if (other.EndTimestampMs != 0L) {
        EndTimestampMs = other.EndTimestampMs;
      }
      matchers_.Add(other.matchers_);
      if (other.hints_ != null) {
        if (hints_ == null) {
          Hints = new global::Prometheus.ReadHints();
        }
        Hints.MergeFrom(other.Hints);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartTimestampMs = input.ReadInt64();
            break;
          }
          case 16: {
            EndTimestampMs = input.ReadInt64();
            break;
          }
          case 26: {
            matchers_.AddEntriesFrom(input, _repeated_matchers_codec);
            break;
          }
          case 34: {
            if (hints_ == null) {
              Hints = new global::Prometheus.ReadHints();
            }
            input.ReadMessage(Hints);
            break;
          }
        }
      }
    }

  }

  public sealed partial class QueryResult : pb::IMessage<QueryResult> {
    private static readonly pb::MessageParser<QueryResult> _parser = new pb::MessageParser<QueryResult>(() => new QueryResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QueryResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Prometheus.RemoteReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryResult(QueryResult other) : this() {
      timeseries_ = other.timeseries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryResult Clone() {
      return new QueryResult(this);
    }

    /// <summary>Field number for the "timeseries" field.</summary>
    public const int TimeseriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Prometheus.TimeSeries> _repeated_timeseries_codec
        = pb::FieldCodec.ForMessage(10, global::Prometheus.TimeSeries.Parser);
    private readonly pbc::RepeatedField<global::Prometheus.TimeSeries> timeseries_ = new pbc::RepeatedField<global::Prometheus.TimeSeries>();
    /// <summary>
    /// Samples within a time series must be ordered by time.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Prometheus.TimeSeries> Timeseries {
      get { return timeseries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QueryResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QueryResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!timeseries_.Equals(other.timeseries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= timeseries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      timeseries_.WriteTo(output, _repeated_timeseries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += timeseries_.CalculateSize(_repeated_timeseries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QueryResult other) {
      if (other == null) {
        return;
      }
      timeseries_.Add(other.timeseries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            timeseries_.AddEntriesFrom(input, _repeated_timeseries_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
