services:
  kustoremotewrite:
    image: kustoremotewrite:latest
    container_name: kustoremotewrite
    ports:
    - "8080:8080"
    - "8081:8081"

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"

  avalanche:
    image: quay.io/freshtracks.io/avalanche:latest
    hostname: avalanche
    ports:
    - "9001:9001"
