// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gogoproto/gogo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gogoproto {

  /// <summary>Holder for reflection information generated from gogoproto/gogo.proto</summary>
  public static partial class GogoReflection {

    #region Descriptor
    /// <summary>File descriptor for gogoproto/gogo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GogoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRnb2dvcHJvdG8vZ29nby5wcm90bxIJZ29nb3Byb3RvGiBnb29nbGUvcHJv",
            "dG9idWYvZGVzY3JpcHRvci5wcm90bzo7ChNnb3Byb3RvX2VudW1fcHJlZml4",
            "EhwuZ29vZ2xlLnByb3RvYnVmLkVudW1PcHRpb25zGLHkAyABKAg6PQoVZ29w",
            "cm90b19lbnVtX3N0cmluZ2VyEhwuZ29vZ2xlLnByb3RvYnVmLkVudW1PcHRp",
            "b25zGMXkAyABKAg6NQoNZW51bV9zdHJpbmdlchIcLmdvb2dsZS5wcm90b2J1",
            "Zi5FbnVtT3B0aW9ucxjG5AMgASgIOjcKD2VudW1fY3VzdG9tbmFtZRIcLmdv",
            "b2dsZS5wcm90b2J1Zi5FbnVtT3B0aW9ucxjH5AMgASgJOjAKCGVudW1kZWNs",
            "EhwuZ29vZ2xlLnByb3RvYnVmLkVudW1PcHRpb25zGMjkAyABKAg6QQoUZW51",
            "bXZhbHVlX2N1c3RvbW5hbWUSIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVl",
            "T3B0aW9ucxjRgwQgASgJOjsKE2dvcHJvdG9fZ2V0dGVyc19hbGwSHC5nb29n",
            "bGUucHJvdG9idWYuRmlsZU9wdGlvbnMYmewDIAEoCDo/Chdnb3Byb3RvX2Vu",
            "dW1fcHJlZml4X2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxia",
            "7AMgASgIOjwKFGdvcHJvdG9fc3RyaW5nZXJfYWxsEhwuZ29vZ2xlLnByb3Rv",
            "YnVmLkZpbGVPcHRpb25zGJvsAyABKAg6OQoRdmVyYm9zZV9lcXVhbF9hbGwS",
            "HC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMYnOwDIAEoCDowCghmYWNl",
            "X2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxid7AMgASgIOjQK",
            "DGdvc3RyaW5nX2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxie",
            "7AMgASgIOjQKDHBvcHVsYXRlX2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxl",
            "T3B0aW9ucxif7AMgASgIOjQKDHN0cmluZ2VyX2FsbBIcLmdvb2dsZS5wcm90",
            "b2J1Zi5GaWxlT3B0aW9ucxig7AMgASgIOjMKC29ubHlvbmVfYWxsEhwuZ29v",
            "Z2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKHsAyABKAg6MQoJZXF1YWxfYWxs",
            "EhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKXsAyABKAg6NwoPZGVz",
            "Y3JpcHRpb25fYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKbs",
            "AyABKAg6MwoLdGVzdGdlbl9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9w",
            "dGlvbnMYp+wDIAEoCDo0CgxiZW5jaGdlbl9hbGwSHC5nb29nbGUucHJvdG9i",
            "dWYuRmlsZU9wdGlvbnMYqOwDIAEoCDo1Cg1tYXJzaGFsZXJfYWxsEhwuZ29v",
            "Z2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKnsAyABKAg6NwoPdW5tYXJzaGFs",
            "ZXJfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKrsAyABKAg6",
            "PAoUc3RhYmxlX21hcnNoYWxlcl9hbGwSHC5nb29nbGUucHJvdG9idWYuRmls",
            "ZU9wdGlvbnMYq+wDIAEoCDoxCglzaXplcl9hbGwSHC5nb29nbGUucHJvdG9i",
            "dWYuRmlsZU9wdGlvbnMYrOwDIAEoCDpBChlnb3Byb3RvX2VudW1fc3RyaW5n",
            "ZXJfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGK3sAyABKAg6",
            "OQoRZW51bV9zdHJpbmdlcl9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9w",
            "dGlvbnMYruwDIAEoCDo8ChR1bnNhZmVfbWFyc2hhbGVyX2FsbBIcLmdvb2ds",
            "ZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxiv7AMgASgIOj4KFnVuc2FmZV91bm1h",
            "cnNoYWxlcl9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMYsOwD",
            "IAEoCDpCChpnb3Byb3RvX2V4dGVuc2lvbnNfbWFwX2FsbBIcLmdvb2dsZS5w",
            "cm90b2J1Zi5GaWxlT3B0aW9ucxix7AMgASgIOkAKGGdvcHJvdG9fdW5yZWNv",
            "Z25pemVkX2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxiy7AMg",
            "ASgIOjgKEGdvZ29wcm90b19pbXBvcnQSHC5nb29nbGUucHJvdG9idWYuRmls",
            "ZU9wdGlvbnMYs+wDIAEoCDo2Cg5wcm90b3NpemVyX2FsbBIcLmdvb2dsZS5w",
            "cm90b2J1Zi5GaWxlT3B0aW9ucxi07AMgASgIOjMKC2NvbXBhcmVfYWxsEhwu",
            "Z29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLXsAyABKAg6NAoMdHlwZWRl",
            "Y2xfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLbsAyABKAg6",
            "NAoMZW51bWRlY2xfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25z",
            "GLfsAyABKAg6PAoUZ29wcm90b19yZWdpc3RyYXRpb24SHC5nb29nbGUucHJv",
            "dG9idWYuRmlsZU9wdGlvbnMYuOwDIAEoCDo3Cg9tZXNzYWdlbmFtZV9hbGwS",
            "HC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMYuewDIAEoCDo9ChVnb3By",
            "b3RvX3NpemVjYWNoZV9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlv",
            "bnMYuuwDIAEoCDo7ChNnb3Byb3RvX3Vua2V5ZWRfYWxsEhwuZ29vZ2xlLnBy",
            "b3RvYnVmLkZpbGVPcHRpb25zGLvsAyABKAg6OgoPZ29wcm90b19nZXR0ZXJz",
            "Eh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGIH0AyABKAg6OwoQ",
            "Z29wcm90b19zdHJpbmdlchIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0",
            "aW9ucxiD9AMgASgIOjgKDXZlcmJvc2VfZXF1YWwSHy5nb29nbGUucHJvdG9i",
            "dWYuTWVzc2FnZU9wdGlvbnMYhPQDIAEoCDovCgRmYWNlEh8uZ29vZ2xlLnBy",
            "b3RvYnVmLk1lc3NhZ2VPcHRpb25zGIX0AyABKAg6MwoIZ29zdHJpbmcSHy5n",
            "b29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYhvQDIAEoCDozCghwb3B1",
            "bGF0ZRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiH9AMgASgI",
            "OjMKCHN0cmluZ2VyEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25z",
            "GMCLBCABKAg6MgoHb25seW9uZRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdl",
            "T3B0aW9ucxiJ9AMgASgIOjAKBWVxdWFsEh8uZ29vZ2xlLnByb3RvYnVmLk1l",
            "c3NhZ2VPcHRpb25zGI30AyABKAg6NgoLZGVzY3JpcHRpb24SHy5nb29nbGUu",
            "cHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYjvQDIAEoCDoyCgd0ZXN0Z2VuEh8u",
            "Z29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGI/0AyABKAg6MwoIYmVu",
            "Y2hnZW4SHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYkPQDIAEo",
            "CDo0CgltYXJzaGFsZXISHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlv",
            "bnMYkfQDIAEoCDo2Cgt1bm1hcnNoYWxlchIfLmdvb2dsZS5wcm90b2J1Zi5N",
            "ZXNzYWdlT3B0aW9ucxiS9AMgASgIOjsKEHN0YWJsZV9tYXJzaGFsZXISHy5n",
            "b29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYk/QDIAEoCDowCgVzaXpl",
            "chIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiU9AMgASgIOjsK",
            "EHVuc2FmZV9tYXJzaGFsZXISHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9w",
            "dGlvbnMYl/QDIAEoCDo9ChJ1bnNhZmVfdW5tYXJzaGFsZXISHy5nb29nbGUu",
            "cHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYmPQDIAEoCDpBChZnb3Byb3RvX2V4",
            "dGVuc2lvbnNfbWFwEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25z",
            "GJn0AyABKAg6PwoUZ29wcm90b191bnJlY29nbml6ZWQSHy5nb29nbGUucHJv",
            "dG9idWYuTWVzc2FnZU9wdGlvbnMYmvQDIAEoCDo1Cgpwcm90b3NpemVyEh8u",
            "Z29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGJz0AyABKAg6MgoHY29t",
            "cGFyZRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxid9AMgASgI",
            "OjMKCHR5cGVkZWNsEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25z",
            "GJ70AyABKAg6NgoLbWVzc2FnZW5hbWUSHy5nb29nbGUucHJvdG9idWYuTWVz",
            "c2FnZU9wdGlvbnMYofQDIAEoCDo8ChFnb3Byb3RvX3NpemVjYWNoZRIfLmdv",
            "b2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxii9AMgASgIOjoKD2dvcHJv",
            "dG9fdW5rZXllZBIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxij",
            "9AMgASgIOjEKCG51bGxhYmxlEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0",
            "aW9ucxjp+wMgASgIOi4KBWVtYmVkEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxk",
            "T3B0aW9ucxjq+wMgASgIOjMKCmN1c3RvbXR5cGUSHS5nb29nbGUucHJvdG9i",
            "dWYuRmllbGRPcHRpb25zGOv7AyABKAk6MwoKY3VzdG9tbmFtZRIdLmdvb2ds",
            "ZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY7PsDIAEoCTowCgdqc29udGFnEh0u",
            "Z29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjt+wMgASgJOjEKCG1vcmV0",
            "YWdzEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxju+wMgASgJOjEK",
            "CGNhc3R0eXBlEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjv+wMg",
            "ASgJOjAKB2Nhc3RrZXkSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25z",
            "GPD7AyABKAk6MgoJY2FzdHZhbHVlEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxk",
            "T3B0aW9ucxjx+wMgASgJOjAKB3N0ZHRpbWUSHS5nb29nbGUucHJvdG9idWYu",
            "RmllbGRPcHRpb25zGPL7AyABKAg6NAoLc3RkZHVyYXRpb24SHS5nb29nbGUu",
            "cHJvdG9idWYuRmllbGRPcHRpb25zGPP7AyABKAg6MwoKd2t0cG9pbnRlchId",
            "Lmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY9PsDIAEoCEJFChNjb20u",
            "Z29vZ2xlLnByb3RvYnVmQgpHb0dvUHJvdG9zWiJnaXRodWIuY29tL2dvZ28v",
            "cHJvdG9idWYvZ29nb3Byb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
